version: '3'
services:
  client:
    build: ./client
    ports:
      - '3000-3001:3000-3001'
  server:
    build: ./server
    environment:
      - MONGO_URI=mongodb://mongo:27017/test-db
    ports:
      - '4000:4000'
    depends_on:
      - mongo
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    ports:
      - '27017-27019:27017-27019'
